using Microsoft.Xna.Framework.Input;

namespace Feev.DesktopGL.Input
{
    public enum FeevKeys
    {
        None = Keys.None,

        A = Keys.A,
        B = Keys.B,
        C = Keys.C,
        D = Keys.D, 
        E = Keys.E,
        F = Keys.F,
        G = Keys.G,
        H = Keys.H,
        I = Keys.I,
        J = Keys.J,
        K = Keys.K,
        L = Keys.L, 
        M = Keys.M, 
        N = Keys.N,
        O = Keys.O,
        P = Keys.P,
        Q = Keys.Q,
        R = Keys.R,
        S = Keys.S,
        T = Keys.T,
        U = Keys.U,
        V = Keys.V,
        W = Keys.W,
        X = Keys.X,
        Y = Keys.Y,
        Z = Keys.Z,

        One = Keys.D1,
        Two = Keys.D2,
        Three = Keys.D3,
        Four = Keys.D4,
        Five = Keys.D5,
        Six = Keys.D6,
        Seven = Keys.D7,
        Eight = Keys.D8,
        Nine = Keys.D9,
        Zero = Keys.D0,

        Left = Keys.Left,
        Right = Keys.Right,
        Up = Keys.Up,
        Down = Keys.Down,

        Escape = Keys.Escape,
        Delete = Keys.Delete,
        Space = Keys.Space,
        Tab = Keys.Tab,
        Enter = Keys.Enter,
        BackSpace = Keys.Back,
        Insert = Keys.Insert,
        CapsLock = Keys.CapsLock,
        NumLock = Keys.NumLock,

        LShift = Keys.LeftShift,
        RShift = Keys.RightShift,
        LCtrl = Keys.LeftControl,
        RCtrl = Keys.RightControl,
        LAlt = Keys.LeftAlt,
        RAlt = Keys.RightAlt,

        Period = Keys.OemPeriod,
        Comma = Keys.OemComma,
        Dash = Keys.OemMinus,
        BackSlash = Keys.OemBackslash,

        Divide = Keys.Divide,
        Multiply = Keys.Multiply,
        Plus = Keys.Add,
        Minus = Keys.Subtract,

        NumPad0 = Keys.NumPad0,
        NumPad1 = Keys.NumPad1,
        NumPad2 = Keys.NumPad2,
        NumPad3 = Keys.NumPad3,
        NumPad4 = Keys.NumPad4,
        NumPad5 = Keys.NumPad5,
        NumPad6 = Keys.NumPad6,
        NumPad7 = Keys.NumPad7,
        NumPad8 = Keys.NumPad8,
        NumPad9 = Keys.NumPad9,

        Decimal = Keys.Decimal,

        PageUp = Keys.PageUp,
        PageDown = Keys.PageDown,
        End = Keys.End,
        Home = Keys.Home,

        F1 = Keys.F1,
        F2 = Keys.F2,
        F3 = Keys.F3,
        F4 = Keys.F4,
        F5 = Keys.F5,
        F6 = Keys.F6,
        F7 = Keys.F7,
        F8 = Keys.F8,
        F9 = Keys.F9,
        F10 = Keys.F10,
        F11 = Keys.F11,
		F12 = Keys.F12,
		F13 = Keys.F13,
		F14 = Keys.F14,
		F15 = Keys.F15,
		F16 = Keys.F16,
		F17 = Keys.F17,
		F18 = Keys.F18,
		F19 = Keys.F19,
		F20 = Keys.F20,
		F21 = Keys.F21,
		F22 = Keys.F22,
		F23 = Keys.F23,
		F24 = Keys.F24,

    }
}
