using Microsoft.Xna.Framework.Input;

using MonoKeys = Microsoft.Xna.Framework.Input.Keys;

namespace Feev.DesktopGL.Input
{
    public enum Keys
    {
        None = MonoKeys.None,

        A = MonoKeys.A,
        B = MonoKeys.B,
        C = MonoKeys.C,
        D = MonoKeys.D, 
        E = MonoKeys.E,
        F = MonoKeys.F,
        G = MonoKeys.G,
        H = MonoKeys.H,
        I = MonoKeys.I,
        J = MonoKeys.J,
        K = MonoKeys.K,
        L = MonoKeys.L, 
        M = MonoKeys.M, 
        N = MonoKeys.N,
        O = MonoKeys.O,
        P = MonoKeys.P,
        Q = MonoKeys.Q,
        R = MonoKeys.R,
        S = MonoKeys.S,
        T = MonoKeys.T,
        U = MonoKeys.U,
        V = MonoKeys.V,
        W = MonoKeys.W,
        X = MonoKeys.X,
        Y = MonoKeys.Y,
        Z = MonoKeys.Z,

        One = MonoKeys.D1,
        Two = MonoKeys.D2,
        Three = MonoKeys.D3,
        Four = MonoKeys.D4,
        Five = MonoKeys.D5,
        Six = MonoKeys.D6,
        Seven = MonoKeys.D7,
        Eight = MonoKeys.D8,
        Nine = MonoKeys.D9,
        Zero = MonoKeys.D0,

        Left = MonoKeys.Left,
        Right = MonoKeys.Right,
        Up = MonoKeys.Up,
        Down = MonoKeys.Down,

        Escape = MonoKeys.Escape,
        Delete = MonoKeys.Delete,
        Space = MonoKeys.Space,
        Tab = MonoKeys.Tab,
        Enter = MonoKeys.Enter,
        BackSpace = MonoKeys.Back,
        Insert = MonoKeys.Insert,
        CapsLock = MonoKeys.CapsLock,
        NumLock = MonoKeys.NumLock,

        LShift = MonoKeys.LeftShift,
        RShift = MonoKeys.RightShift,
        LCtrl = MonoKeys.LeftControl,
        RCtrl = MonoKeys.RightControl,
        LAlt = MonoKeys.LeftAlt,
        RAlt = MonoKeys.RightAlt,
        LWindows = MonoKeys.LeftWindows,
        RWindows = MonoKeys.RightWindows,

        Period = MonoKeys.OemPeriod,
        Comma = MonoKeys.OemComma,
        Dash = MonoKeys.OemMinus,
        BackSlash = MonoKeys.OemBackslash,
        OemQuotes = MonoKeys.OemQuotes,

        Divide = MonoKeys.Divide,
        Multiply = MonoKeys.Multiply,
        Plus = MonoKeys.Add,
        Minus = MonoKeys.Subtract,

        NumPad0 = MonoKeys.NumPad0,
        NumPad1 = MonoKeys.NumPad1,
        NumPad2 = MonoKeys.NumPad2,
        NumPad3 = MonoKeys.NumPad3,
        NumPad4 = MonoKeys.NumPad4,
        NumPad5 = MonoKeys.NumPad5,
        NumPad6 = MonoKeys.NumPad6,
        NumPad7 = MonoKeys.NumPad7,
        NumPad8 = MonoKeys.NumPad8,
        NumPad9 = MonoKeys.NumPad9,

        Decimal = MonoKeys.Decimal,

        PageUp = MonoKeys.PageUp,
        PageDown = MonoKeys.PageDown,
        End = MonoKeys.End,
        Home = MonoKeys.Home,
        PrintScreen = MonoKeys.PrintScreen,

        F1 = MonoKeys.F1,
        F2 = MonoKeys.F2,
        F3 = MonoKeys.F3,
        F4 = MonoKeys.F4,
        F5 = MonoKeys.F5,
        F6 = MonoKeys.F6,
        F7 = MonoKeys.F7,
        F8 = MonoKeys.F8,
        F9 = MonoKeys.F9,
        F10 = MonoKeys.F10,
        F11 = MonoKeys.F11,
		F12 = MonoKeys.F12,
		F13 = MonoKeys.F13,
		F14 = MonoKeys.F14,
		F15 = MonoKeys.F15,
		F16 = MonoKeys.F16,
		F17 = MonoKeys.F17,
		F18 = MonoKeys.F18,
		F19 = MonoKeys.F19,
		F20 = MonoKeys.F20,
		F21 = MonoKeys.F21,
		F22 = MonoKeys.F22,
		F23 = MonoKeys.F23,
		F24 = MonoKeys.F24,


        Pause = MonoKeys.Pause,
        Apps = MonoKeys.Apps,
        Scroll = MonoKeys.Scroll,

        MediaPlayPause = MonoKeys.MediaPlayPause,
        MediaStop = MonoKeys.MediaStop,
        MediaNext = MonoKeys.MediaNextTrack,
        MediaPrevious = MonoKeys.MediaPreviousTrack,

        VolumeUp = MonoKeys.VolumeUp,
        VolumeDown = MonoKeys.VolumeDown,
        VolumeMute = MonoKeys.VolumeMute,
    }
}
